# Generated by Django 4.2.7 on 2026-07-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario'), (3, 'Fabricante')], default=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario'), (3, 'Fabricante')], default=2),
        ),
    ]
